// Действия над пользователями
export const GET_USERS_REQUEST = 'GET_USERS_REQUEST';
export const GET_USERS_SUCCESS = 'GET_USERS_SUCCESS';
export const GET_USERS_FAILURE = 'GET_USERS_FAILURE';

// Действия над снами
export const GET_DREAMS_REQUEST    = 'GET_DREAMS_REQUEST';
export const GET_DREAMS_SUCCESS    = 'GET_DREAMS_SUCCESS';
export const GET_DREAMS_FAILURE    = 'GET_DREAMS_FAILURE';
export const GET_DREAM_REQUEST     = 'GET_DREAM_REQUEST';
export const GET_DREAM_SUCCESS     = 'GET_DREAM_SUCCESS';
export const GET_DREAM_FAILURE     = 'GET_DREAM_FAILURE';
export const RESET_DREAM_FORM      = 'RESET_DREAM_FORM';
export const ADD_DREAM_PREPARE     = 'ADD_DREAM_PREPARE';
export const ADD_DREAM_REQUEST     = 'ADD_DREAM_REQUEST';
export const ADD_DREAM_SUCCESS     = 'ADD_DREAM_SUCCESS';
export const ADD_DREAM_FAILURE     = 'ADD_DREAM_FAILURE';
export const EDIT_DREAM_REQUEST    = 'EDIT_DREAM_REQUEST';
export const EDIT_DREAM_SUCCESS    = 'EDIT_DREAM_SUCCESS';
export const EDIT_DREAM_FAILURE    = 'EDIT_DREAM_FAILURE';
export const DELETE_DREAM_REQUEST  = 'DELETE_DREAM_REQUEST';
export const DELETE_DREAM_SUCCESS  = 'DELETE_DREAM_SUCCESS';
export const DELETE_DREAM_FAILURE  = 'DELETE_DREAM_FAILURE';
export const DELETE_DREAMS_REQUEST = 'DELETE_DREAMS_REQUEST';
export const DELETE_DREAMS_SUCCESS = 'DELETE_DREAMS_SUCCESS';
export const DELETE_DREAMS_FAILURE = 'DELETE_DREAMS_FAILURE';
export const SELECT_DREAMS         = 'SELECT_DREAMS';
export const UNSELECT_DREAMS       = 'UNSELECT_DREAMS';
export const SELECT_DREAM          = 'SELECT_DREAM';
export const UNSELECT_DREAM        = 'UNSELECT_DREAM';
export const RESET_SELECTED_DREAMS = 'RESET_SELECTED_DREAMS';